title: Multiverse by HTML5 UP
author: João Neto
email: joao@neto.pt
description: >-
  Antero - minimalist clothing

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
