title: Adventskalender
author: Alejandro Prieto
email: none
description: >-
  Adventskalender für amor

social:
  twitter: none
  facebook: none
  instagram: none
  github: none
  linkedin: none

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
