title: Antero
author: antero studio
email: info@antero.studio
description: >-
  Antero - minimalist clothing

social:
  twitter: antero.studio
  facebook: antero.studio
  instagram: antero.studio
  github: antero.studio
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
